# application.yml - Configuración principal
spring:
  application:
    name: sistema-stock-backend
  
  # Configuración de Base de Datos
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_stock_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: stock_user
    password: stock_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # Configuración JPA
  jpa:
    hibernate:
      ddl-auto: validate  # Importante: validate para usar solo Flyway
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: false
  
  # Configuración Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true  # Seguridad: no permitir limpiar BD
    
  # DevTools (solo desarrollo)
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Configuración del servidor
server:
  port: 8080
  servlet:
    context-path: /api

# Logging
logging:
  level:
    com.sistemastock: DEBUG
    org.springframework.web: DEBUG
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator (monitoreo)
management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway
  endpoint:
    health:
      show-details: always


# Perfil de desarrollo
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_stock_db_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


# Perfil de producción  
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql:3306/sistema_stock_db?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:stock_user}
    password: ${DB_PASSWORD:stock_password}
  jpa:
    show-sql: false
  flyway:
    clean-disabled: true